repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: cd oapen-engine && pipenv run isort src/
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: cd oapen-engine && pipenv run black src/
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: cd oapen-engine && pipenv run flake8 src/
        types: [python]
        exclude: setup.py

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: cd oapen-engine && pipenv run pytest
        types: [python]