version: "3.8"
services:
  oapen-engine :
    build: ./oapen-engine/
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
    # TODO change
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    build: ./api/
  web:
    build: ./web/
volumes:
  db:
    driver: local
