version: "3.8"
services:
  oapen-engine :
    build: ./oapen-engine/
    environment:
      - RUN_CLEAN=1
      - COLLECTION_IMPORT_LIMIT=0   # Set to 0 for full harvest
      - REFRESH_PERIOD=50400        # twice weekly
      - HARVEST_PERIOD=604800       # weekly
  api:
    build: ./api/
    expose:
       - 3001
    ports:
        - "0.0.0.0:3001:3001"
  web:
    build: ./web/
    expose:
        - 3000
    ports:
        - "0.0.0.0:3000:3000"
volumes:
  db:
    driver: local
