version: "3.8"
services:
  oapen-engine :
    build: ./oapen-engine/
    restart: always
    env_file:
      - .env
  api:
    container_name: api
    build: ./api/
    restart: always
    env_file:
      - .env
    ports:
      - 0.0.0.0:${API_PORT}:${API_PORT}
    networks:
      - nginx-passthrough
  nginx:
    image: nginx:mainline-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx/templates
      - /etc/certbot/conf:/etc/letsencrypt
      - /etc/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-passthrough
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - /etc/certbot/conf:/etc/letsencrypt
      - /etc/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${SSL_EMAIL} -d ${DOMAIN} --agree-tos
  web:
    build: ./web/
    restart: always
    ports:
        - "0.0.0.0:${WEB_DEMO_PORT}:3000"
  embed-script-test:
    build: ./embed-script/
    restart: always
    ports:
        - "0.0.0.0:${EMBED_SCRIPT_PORT}:3002"
networks:
  nginx-passthrough:
    driver: bridge