version: "3.8"
services:
  oapen-engine :
    build: ./oapen-engine/
    restart: always
    env_file:
      - .env
    environment:
      - COLLECTION_IMPORT_LIMIT=0   # Set to 0 for full harvest
      - REFRESH_PERIOD=86400        # daily
      - HARVEST_PERIOD=604800       # weekly
  api:
    container_name: api
    build: ./api/
    restart: always
    env_file:
      - .env
    ports:
        - "0.0.0.0:${API_PORT}:${API_PORT}"
    networks:
      - nginx-passthrough
  nginx:
    image: nginx:mainline-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: always
    networks:
      - nginx-passthrough
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
  web:
    build: ./web/
    restart: always
    ports:
        - "0.0.0.0:${WEB_DEMO_PORT}:3000"
  embed-script-test:
    build: ./embed-script/
    restart: always
    ports:
        - "0.0.0.0:${EMBED_SCRIPT_PORT}:3002"
networks:
  nginx-passthrough:
    driver: bridge
