version: "3.8"
services:
  oapen-engine :
    build: ./oapen-engine/
  api:
    build: ./api/
    expose:
       - 3001
    ports:
        - "0.0.0.0:3001:3001"
  web:
    build: ./web/
    expose:
        - 3000
    ports:
        - "0.0.0.0:3000:3000"
volumes:
  db:
    driver: local
