version: "3.8"
services:
  oapen-engine :
    build: ./oapen-engine/
    env_file:
      - .env
    environment:
      - RUN_CLEAN=1
      - COLLECTION_IMPORT_LIMIT=0   # Set to 0 for full harvest
      - REFRESH_PERIOD=86400        # daily
      - HARVEST_PERIOD=604800       # weekly
  api:
    build: ./api/
    env_file:
      - .env
    expose:
       - ${API_PORT}
    ports:
        - "0.0.0.0:${API_PORT}:${API_PORT}"
  web:
    build: ./web/
    expose:
        - ${WEB_DEMO_PORT}
    ports:
        - "0.0.0.0:${WEB_DEMO_PORT}:${WEB_DEMO_PORT}"
  embed-script-test:
    build: ./embed-script/
    expose:
        - ${EMBED_SCRIPT_PORT}
    ports:
        - "0.0.0.0:${EMBED_SCRIPT_PORT}:${EMBED_SCRIPT_PORT}"
volumes:
  db:
    driver: local
