name: OAPEN Engine

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install dependencies with pipenv
        working-directory: ./oapen-engine
        run: |
          pip install pipenv
          pipenv install

      - name: Lint + Test
        run: |
          pipenv run isort
      - run: pipenv run black --check .
      - run: pipenv run flake8
      - run: pipenv run pytest
      