name: OAPEN Engine

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - name: Install pipenv
        working-directory: ./oapen-engine
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        
      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install
          pipenv shell

      - name: Lint
         run: |
          pipenv run black --check .
          pipenv run flake8

      - name: Test
        - run: pipenv run pytest
      