name: OAPEN Engine

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3.10.7
        with:
          python-version: 3.10
        
      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev
      - run: pipenv run isort --recursive --diff
      - run: pipenv run black --check .
      - run: pipenv run pytest
      