name: OAPEN Engine

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - name: Install pipenv
        run: |
          cd oapen-engine
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        
      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev
          pipenv run isort --recursive --diff
          pipenv run black --check .
          pipenv run pytest
      